### ISSUE TITLE
Translate FnO expressions

### ISSUE THREAD

**Issue by LuisLopezPi** [citiususc/yatter#15]
Functions are not yet implemented in the parser.

**Comment by dachafra** [comment]
We are not going to support functions atm, we will wait till a [community draft specification](https://github.com/kg-construct/rml-fno-spec)

**Comment by dachafra** [comment]
As the CG-W3C draft has been already provided, we can now start the supporting

**Comment by dachafra** [comment]
Finally solved! #47
