### ISSUE TITLE
Import error  import yarrrml-translator => ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by shakeel26** [citiususc/yatter#31]
Command line version works well but in the second version where I want to use as module there is basic error in import. 

```
import yarrrml-translator
                  ^
SyntaxError: invalid syntax(url)
```

Installation didn't have any issue.

**Comment by dachafra** [comment]
Hi @shakeel26,
Thanks for using the tool. I've modified the module name, renaming it to `yarrrrml_translator` as module names cannot have a dash in their names. A new version (v.0.6.3) is published. Please let me know if has been solved
