### ISSUE TITLE
Create dictionary for yarrrml keys

### ISSUE THREAD

**Issue by arenas-guerrero-julian** [citiususc/yatter#34]
[ods-yarrrml-toolkit](https://github.com/benj-moreau/ods-yarrrml-toolkit) is a library in python to convert heterogeneous data to RDF using YARRRML.

Although it is not the same than this tool, maybe some code can be reused (if the license allows so). For instance they use regex expressions that look (at a fast glance) cleaner that the matching that the yarrrml-translator is doing.

**Comment by dachafra** [comment]
After an analysis of the script, the only interesting part that could be reused here is the `yarrrml` keys dictionary, to support all (shortcuts and expanded ones) in a more optimal way.

**Comment by dachafra** [comment]
Dictionaries for keys names have been implemented ([see here](https://github.com/oeg-upm/yarrrml-translator/blob/v0.8.2/yarrrml-translator/yarrrml_translator/constants.py#L169)). However, at this moment we cannot see any relevant point on how they can help to improve the access to the data, but we will study it in a potential code refactoring for future versions.

After analyzing as well the regex expressions, they are very simple and do not cover other potential cases (see for example [XPath expressions with references in the PPDS mappings](https://github.com/oeg-upm/yarrrml-translator/blob/v0.8.2/test/projects/PPDSTC/mapping.yml)), where other YARRRML parsers fail.  Retrieving complex templates from YARRRML [has been updated](https://github.com/oeg-upm/yarrrml-translator/blob/v0.8.2/yarrrml-translator/yarrrml_translator/termmap.py#L25) to consider also these cases.

I think we can close this issue.
