### ISSUE TITLE
AttributeError: partially initialized module 'yarrrml_translator' has no attribute 'translate' (most likely due to a circular import)

### ISSUE THREAD

**Issue by shakeel26** [citiususc/yatter#35]
Command line version is working fine but when I want to include the module in your implementation where I am just using the simple example:
```
import yarrrml_translator
import yaml
rml_content = yarrrml_translator.translate(yaml.safe_load(open("yarrml.yml")))
print(rml_content)
```

Here is the error:
AttributeError: partially initialized module 'yarrrml_translator' has no attribute 'translate' (most likely due to a circular import)
![Screenshot from 2022-10-25 23-15-38](https://user-images.githubusercontent.com/45169340/197883533-93e14b06-f0e1-4927-b9c2-bda93901dd62.png)

Can you please check ?

**Comment by dachafra** [comment]
I run this in a google collab notebook and it works. I think this is related to #36, and once solved, it will work

<img width="1088" alt="Captura de Pantalla 2022-10-26 a las 11 56 47" src="https://user-images.githubusercontent.com/12400271/197996650-9bff17f5-8d39-4d5f-be25-5a27f3ccb16f.png">

**Comment by shakeel26** [comment]
I have upgraded `python3.8` to `3.9` and then on installation 
`pip install yarrrml-translator`
![Screenshot from 2022-10-26 17-13-05](https://user-images.githubusercontent.com/45169340/198065512-f2963b63-de7e-4965-aa5a-6225eb5aa81e.png)

Installation works I believe.
but still on running the file with module import I have the above error ```AttributeError: partially initialized module 'yarrrml_translator' has no attribute 'translate' (most likely due to a circular import)
```

**Comment by dachafra** [comment]
What is reported there is that you already have installed the engine. 
My suggestion would be to create a virtual environment and install it, as it seems an error on your imports. You can create requirements.txt with your dependencies and install them as `python3 -m pip install -r requirements.txt`. 
To be honest, I don't think this is a related issue with the engine as it has been tested that it works in google collab.
This and #36 will be closed.
