### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by shakeel26** [citiususc/yatter#36]
I have posted another issue before which doesn't allow to run as module while works in CMD version:

Now I see that installation also has issues, can you please check ?
When I try to install with below command, error is shown in the screenshot
`pip install yarrrml-translator`
![Screenshot from 2022-10-25 23-20-03](https://user-images.githubusercontent.com/45169340/197884333-79b83faa-75b9-4e73-a087-dfafcb92a930.png)

**Comment by dachafra** [comment]
Hi, I don't think this is an error in the code or the module. It says that pip is not installed or found on your computer. Which OS are you using?

In any case, I run the installation command in a google collab and it works.
<img width="1595" alt="image" src="https://user-images.githubusercontent.com/12400271/197992800-020aeba2-4314-41b3-be9d-a846657303eb.png">

**Comment by shakeel26** [comment]
I'm using Ubuntu

**Comment by dachafra** [comment]
I would suggest checking your python installation, as it seems that you don't have pip installed. I'm running this with `Python 3.9.6` and `pip 22.2.2`

**Comment by shakeel26** [comment]
I have `Python 3.8.10` and  `pip 22.2.2 `

**Comment by dachafra** [comment]
Try to run `python3 -m pip install yarrrml-translator`

**Comment by dachafra** [comment]
I'll update the requirement of having `python3.9` installed.

**Comment by dachafra** [comment]
Tested the engine over python 3.7 and it works, setup updated to that version
