### ISSUE TITLE
Test all pretty generated output

### ISSUE THREAD

**Issue by DylanVanAssche** [citiususc/yatter#54]
This YARRRML translator is able to nicely format YARRRML <--> RML transformations. It would be great to test this as well besides comparing the generated RML RDF to make sure that the prettyness stays pretty when changes are applied :)

This can achieved by parsing the expected output file as a string and compare it with the generated string.
If the formatting differs, the test fails.

**Comment by dachafra** [comment]
Implemented for all R2RML cases, which atm is enough IMO
