### ISSUE TITLE
Mappings need rr:TriplesMap to transform [R2]RML into YARRRML

### ISSUE THREAD

**Issue by DiegoCondeHerreros** [citiususc/yatter#57]
**Describe the bug**
When attempting to transform the mappings from the "Base topológica nacional BTN100" dataset from RML into YARRRML formt the file is created but the mappings section is empty.

**To Reproduce**
1. Execute the command "python3 -m yatter -i btn100mappings.ttl -o btn_yarrrml.yml" as stated in the tutorial present in the repository.

**Input Data**
[btn100mappings.zip](https://github.com/oeg-upm/yatter/files/11098414/btn100mappings.zip)

**Screenshot of the output.**
![yarmlecreenshot](https://user-images.githubusercontent.com/63185386/228478765-fa6dda15-d655-401a-acc2-826a2a496b08.jpg)

**Comment by dachafra** [comment]
This is not a bug... the mapping is in R2RML, not RML, so needs to indicate the input format:
`python3 -m yatter -i btn100mappings.ttl -o btn_yarrrml.yml -f R2RML`
[mapping.yml.txt](https://github.com/oeg-upm/yatter/files/11098749/mapping.yml.txt)

**Comment by dachafra** [comment]
This has been solved!
